#!/bin/sh

read -p "Renaming player '$1' to '$2'. Do you wish to continue? " yn
case $yn in
    [Yy]* ) break;;
    [Nn]* ) exit;;
    * ) echo "Please answer yes or no.";;
esac

find . -type f -exec sed -i "s/$1/$2/g" {} \;
